{"name": " -- @1.3 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//button[text()=\"CONTINUE\"]\"}\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00FFACD3+2075859]\n\tOrdinal0 [0x00F8EE61+1633889]\n\tOrdinal0 [0x00E8B7BD+571325]\n\tOrdinal0 [0x00EBAC2F+764975]\n\tOrdinal0 [0x00EBAE1B+765467]\n\tOrdinal0 [0x00EED0F2+970994]\n\tOrdinal0 [0x00ED7364+881508]\n\tOrdinal0 [0x00EEB56A+963946]\n\tOrdinal0 [0x00ED7136+880950]\n\tOrdinal0 [0x00EAFEFD+720637]\n\tOrdinal0 [0x00EB0F3F+724799]\n\tGetHandleVerifier [0x012AEED2+2769538]\n\tGetHandleVerifier [0x012A0D95+2711877]\n\tGetHandleVerifier [0x0108A03A+521194]\n\tGetHandleVerifier [0x01088DA0+516432]\n\tOrdinal0 [0x00F9682C+1665068]\n\tOrdinal0 [0x00F9B128+1683752]\n\tOrdinal0 [0x00F9B215+1683989]\n\tOrdinal0 [0x00FA6484+1729668]\n\tBaseThreadInitThunk [0x7675FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x776B7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x776B7B8E+238]\n\n", "trace": "  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pharmeasy_test.py\", line 85, in click_continue\n    context.driver.find_element(\"xpath\", '//button[text()=\"CONTINUE\"]').click()\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given User should be able to launch the browser", "status": "passed", "start": 1667455091771, "stop": 1667455121977}, {"name": "Then User should be able to enter homepage of pharmeasy application", "status": "passed", "start": 1667455121978, "stop": 1667455135916}, {"name": "When User should be able to click on medicine module", "status": "passed", "start": 1667455135916, "stop": 1667455154813}, {"name": "And User should be able to click on pincode", "status": "passed", "start": 1667455154813, "stop": 1667455155005}, {"name": "Then User should be able to enter \"560001\"", "status": "passed", "start": 1667455155006, "stop": 1667455155355}, {"name": "And User should be able to click on submit", "status": "passed", "start": 1667455155355, "stop": 1667455160524}, {"name": "Then User should be able to search for \"dolo\"", "status": "passed", "start": 1667455160525, "stop": 1667455160740}, {"name": "And User is able to click on search button", "status": "passed", "start": 1667455160741, "stop": 1667455160880}, {"name": "And User should be able to select the product", "status": "passed", "start": 1667455160881, "stop": 1667455162876}, {"name": "Then User should be able to select quantity", "status": "passed", "start": 1667455162876, "stop": 1667455163309}, {"name": "And User is able to click on view cart", "status": "passed", "start": 1667455163309, "stop": 1667455173312}, {"name": "And User is able to add delivery address", "status": "passed", "start": 1667455173312, "stop": 1667455173635}, {"name": "Then User is able to login with \"9008240114`\"", "status": "passed", "start": 1667455173636, "stop": 1667455174403}, {"name": "And User is able to click on send otp", "status": "passed", "start": 1667455174403, "stop": 1667455194685}, {"name": "And User should be able to click on continue", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//button[text()=\"CONTINUE\"]\"}\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00FFACD3+2075859]\n\tOrdinal0 [0x00F8EE61+1633889]\n\tOrdinal0 [0x00E8B7BD+571325]\n\tOrdinal0 [0x00EBAC2F+764975]\n\tOrdinal0 [0x00EBAE1B+765467]\n\tOrdinal0 [0x00EED0F2+970994]\n\tOrdinal0 [0x00ED7364+881508]\n\tOrdinal0 [0x00EEB56A+963946]\n\tOrdinal0 [0x00ED7136+880950]\n\tOrdinal0 [0x00EAFEFD+720637]\n\tOrdinal0 [0x00EB0F3F+724799]\n\tGetHandleVerifier [0x012AEED2+2769538]\n\tGetHandleVerifier [0x012A0D95+2711877]\n\tGetHandleVerifier [0x0108A03A+521194]\n\tGetHandleVerifier [0x01088DA0+516432]\n\tOrdinal0 [0x00F9682C+1665068]\n\tOrdinal0 [0x00F9B128+1683752]\n\tOrdinal0 [0x00F9B215+1683989]\n\tOrdinal0 [0x00FA6484+1729668]\n\tBaseThreadInitThunk [0x7675FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x776B7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x776B7B8E+238]\n\n", "trace": "  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pharmeasy_test.py\", line 85, in click_continue\n    context.driver.find_element(\"xpath\", '//button[text()=\"CONTINUE\"]').click()\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667455194686, "stop": 1667455214763}, {"name": "And User should be able to click on save", "status": "skipped", "start": 1667455214765, "stop": 1667455214765}], "parameters": [{"name": "pincode", "value": "560001"}, {"name": "medicine", "value": "dolo"}, {"name": "mobile_number", "value": "9008240114`"}], "start": 1667455091766, "stop": 1667455214765, "uuid": "abf00c3c-3d57-46be-970e-659b8a9a6bdf", "historyId": "d21e39e8b1bb75532fdd4ea127cfb7d8", "fullName": "Medicine_module: ", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Medicine_module"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}